# Site settings
title: "Tastyfish's Site"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://tastyfish.github.io" # the base hostname & protocol for your site
github_username:  tastyfish

# Build settings
markdown: kramdown
